language: python

sudo: false

cache:
  pip: true

python:
  - 2.7

services:
  - docker

install:
  - pip install -U tox-travis codecov

script: tox

after_success:
  - codecov --disable search

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: leukgen
  password: <TO REPLACE THIS RUN `travis encrypt --add deploy.password`>
  on:
    tags: true
    repo: leukgen/toil_example
    python: 2.7
    branch: master
